#########################
## Sample Sass Lint File
#########################
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  # formatters https://github.com/eslint/eslint/tree/master/lib/formatters
  # formatter: compact
  # Output file instead of logging results
  # output-file: 'linters/sass-lint.html'
# File Options
files:
  include:
    - 'src/styles/**.*scss'
  ignore:
    - 'src/styles/vendor/**/*.*'
    - 'src/styles/normalize.scss'
# Rule Configuration
rules:
  id-name-format:
    - 1
    -
      convention: ^[_A-Z]+$
      convention-explanation: 'IDs must contain only uppercase letters and underscores'
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq
  nesting-depth:
    - 1
    -
      max-depth: 13
  no-warn: 1
  no-debug: 1
  no-ids: 1
  no-important: 2
  hex-notation: 1
  indentation:
    - 2
    -
      size: 2
  property-sort-order:
    - 1
    -
      order: concentric
      ignore-custom-properties: true
  leading-zero:
    - 1
    -
      include: true
  variable-for-property:
    - 2
    -
      properties:
        - margin
        - content
